version: '3.4'

services:
    localtunnel:
        image: devenda/sshtunnel
        build: ./Tunnel
        container_name: localtunnel
        environment:
        - SSH_HOSTUSER=ecofablab
        - SSH_HOSTNAME=67.205.12.211 #chondu.dreamhost.com
        - SSH_TUNNEL_REMOTE=3306
        - SSH_TUNNEL_HOST=208.97.161.118 #mysql.ecofablab.be
        - SSH_TUNNEL_LOCAL=3306 #mysql.ecofablab.be mysql port
        - SSH_MODE=-Ng -L #Local forward mode (vs -R remote forward mode)
        - SSH_KEY_FILE=/ssh/id_rsa  
        restart: always
        volumes:
        - ./Tunnel:/key #mount host current directory ./sshTunnel to container /key
        dns:
        - 8.8.8.8
        - 4.2.2.4
    remotetunnel:
        image: devenda/sshtunnel
        container_name: remotetunnel
        environment:
        - SSH_HOSTUSER=ecofablab
        - SSH_HOSTNAME=67.205.12.211 #chondu.dreamhost.com
        - SSH_TUNNEL_REMOTE=22222
        - SSH_TUNNEL_HOST=host.docker.internal #resolves to ip of host
        - SSH_TUNNEL_LOCAL=80 #API port
        - SSH_MODE=-R #Local forward mode (vs -R remote forward mode)
        - SSH_KEY_FILE=/ssh/id_rsa  
        restart: always
        volumes:
        - ./Tunnel:/key #mount host current directory ./sshTunnel to container /key
        # dns: # when using DNS does not resolve host.docker.internal
        # - 8.8.8.8
        # - 4.2.2.4
    tunnel-tester:
        image: tunneltester
        build: ./TunnelTester
        container_name: tunnel-tester
        restart: always
        tty: true
        stdin_open: true